# Generated by Django 2.0 on 2020-05-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teamuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='company',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='job',
        ),
        migrations.AddField(
            model_name='teams',
            name='max_number',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='teams',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamuser',
            name='company',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teamuser',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamuser',
            name='job',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
