# Generated by Django 2.0 on 2020-05-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200502_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
