# Generated by Django 2.0 on 2020-05-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200502_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamuser',
            old_name='point',
            new_name='points',
        ),
    ]
