# Generated by Django 2.0 on 2020-05-03 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200502_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='max_number',
        ),
        migrations.AddField(
            model_name='teams',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamuser',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
