# Generated by Django 2.0 on 2020-05-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manage_Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctf_name', models.CharField(default='CTF', max_length=100)),
                ('match_name', models.CharField(default='CTF', max_length=100)),
                ('first_blood', models.IntegerField(default=0)),
                ('second_blood', models.IntegerField(default=0)),
                ('third_blood', models.IntegerField(default=0)),
            ],
        ),
    ]
