# Generated by Django 2.0 on 2020-05-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_match',
            name='start_submit',
            field=models.BooleanField(default=False),
        ),
    ]
