# Generated by Django 2.0 on 2020-05-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_manage_match_start_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_match',
            name='team_max_number',
            field=models.IntegerField(default=3),
        ),
    ]
